' filepath: /home/rafa-so/workspace/pessoal/bet-familia-core/docs/core-schema.puml
@startuml "schema bet familia"

!theme plain
hide circle
skinparam linetype ortho

entity "User" as user {
  * id : uuid <<PK>>
  --
  name : varchar
  email : varchar <<Nullable>>
  is_managed : boolean (default false)
  total_points : integer
}

entity "Tournament" as tournament {
  * id : uuid <<PK>>
  --
  name : varchar
  config : jsonb
}

entity "Match" as match {
  * id : uuid <<PK>>
  --
  * tournament_id : uuid <<FK>>
  team_home : varchar
  team_away : varchar
  start_at : timestamp
  home_score : integer
  away_score : integer
  status : enum
}

entity "Bet" as bet {
  * id : uuid <<PK>>
  --
  * user_id : uuid <<FK>> (Dono da aposta)
  * created_by_id : uuid <<FK>> (Quem digitou)
  * match_id : uuid <<FK>>
  bet_home_score : integer
  bet_away_score : integer
  points_earned : integer
}

user ||--o{ bet : "ganha pontos"
user ||--o{ bet : "registra"
tournament ||--o{ match : "contém"
match ||--o{ bet : "recebe"

@enduml